// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!
//
use pyo3::prelude::*;
mod r#async_fetch_object;
mod r#batch_ops;
mod r#copy_object;
mod r#create_bucket;
mod r#delete_bucket;
mod r#delete_bucket_taggings;
mod r#delete_object;
mod r#fetch_object;
mod r#get_async_fetch_task;
mod r#get_bucket_taggings;
mod r#get_buckets;
mod r#get_domains;
mod r#get_objects;
mod r#get_objects_v2;
mod r#modify_object_life_cycle;
mod r#modify_object_metadata;
mod r#modify_object_status;
mod r#move_object;
mod r#prefetch_object;
mod r#put_object;
mod r#restore_archived_object;
mod r#resumable_upload_v1_bput;
mod r#resumable_upload_v1_make_block;
mod r#resumable_upload_v1_make_file;
mod r#resumable_upload_v2_abort_multipart_upload;
mod r#resumable_upload_v2_complete_multipart_upload;
mod r#resumable_upload_v2_initiate_multipart_upload;
mod r#resumable_upload_v2_list_parts;
mod r#resumable_upload_v2_upload_part;
mod r#set_bucket_private;
mod r#set_bucket_taggings;
mod r#set_buckets_mirror;
mod r#set_object_file_type;
mod r#stat_object;
pub(super) fn create_module(py: Python<'_>) -> PyResult<&PyModule> {
    let m = PyModule::new(py, "storage")?;
    m.add_submodule(r#async_fetch_object::create_module(py)?)?;
    m.add_submodule(r#batch_ops::create_module(py)?)?;
    m.add_submodule(r#copy_object::create_module(py)?)?;
    m.add_submodule(r#create_bucket::create_module(py)?)?;
    m.add_submodule(r#delete_bucket::create_module(py)?)?;
    m.add_submodule(r#delete_bucket_taggings::create_module(py)?)?;
    m.add_submodule(r#delete_object::create_module(py)?)?;
    m.add_submodule(r#fetch_object::create_module(py)?)?;
    m.add_submodule(r#get_async_fetch_task::create_module(py)?)?;
    m.add_submodule(r#get_bucket_taggings::create_module(py)?)?;
    m.add_submodule(r#get_buckets::create_module(py)?)?;
    m.add_submodule(r#get_domains::create_module(py)?)?;
    m.add_submodule(r#get_objects::create_module(py)?)?;
    m.add_submodule(r#get_objects_v2::create_module(py)?)?;
    m.add_submodule(r#modify_object_life_cycle::create_module(py)?)?;
    m.add_submodule(r#modify_object_metadata::create_module(py)?)?;
    m.add_submodule(r#modify_object_status::create_module(py)?)?;
    m.add_submodule(r#move_object::create_module(py)?)?;
    m.add_submodule(r#prefetch_object::create_module(py)?)?;
    m.add_submodule(r#put_object::create_module(py)?)?;
    m.add_submodule(r#restore_archived_object::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v1_bput::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v1_make_block::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v1_make_file::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v2_abort_multipart_upload::create_module(
        py,
    )?)?;
    m.add_submodule(r#resumable_upload_v2_complete_multipart_upload::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v2_initiate_multipart_upload::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v2_list_parts::create_module(py)?)?;
    m.add_submodule(r#resumable_upload_v2_upload_part::create_module(py)?)?;
    m.add_submodule(r#set_bucket_private::create_module(py)?)?;
    m.add_submodule(r#set_bucket_taggings::create_module(py)?)?;
    m.add_submodule(r#set_buckets_mirror::create_module(py)?)?;
    m.add_submodule(r#set_object_file_type::create_module(py)?)?;
    m.add_submodule(r#stat_object::create_module(py)?)?;
    Ok(m)
}
